application/exercises/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, session
from application.database import Database
from application.exercises.forms import ExerciseForm
import datetime

exercises_blueprint = Blueprint('exercises', __name__,
                                template_folder='templates/')


@exercises_blueprint.route("/add", methods=["GET", "POST"])
def add():
    form = ExerciseForm()
    if form.validate_on_submit():
        flash('Your workout has been added.')
        session['exercise_name'] = form.name.data
        session['exercise_description'] = form.description.data
        if request.method == "POST":
            # save to mongodb database
            name = form.name.data
            description = form.description.data
            # muscles = form.muscles.data
            video_link = form.video_link.data
            images = form.photo.data
            formatted_date = datetime.datetime.today().strftime("%Y-%m-%d")
            Database.insert('exercises', {'name': name,
                                          'description': description,
                                          # 'muscles': muscles,
                                          'video_link': video_link,
                                          'images': images,
                                          'date': formatted_date})
        return redirect(url_for('exercises.add'))

    return render_template('add.html', form=form)


@exercises_blueprint.route("/view", methods=["GET", "POST"])
def view():
    exercises = [
        (exercise["name"],
         exercise["description"]
         )
        for exercise in Database.find_all('exercises')
    ]

    return render_template("view.html", exercises=exercises)

application/workouts/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, session
from application.database import Database
# from application.models import Workout
from application.workouts.forms import WorkoutForm
import datetime

workouts_blueprint = Blueprint('workouts', __name__,
                               template_folder='templates/')


@workouts_blueprint.route("/create", methods=["GET", "POST"])
def create():
    form = WorkoutForm()
    if form.validate_on_submit():
        flash('Your workout has been added.')
        # session['workout_content'] = [form.exercise1.data, form.num_sets1, form.num_reps1.data]
        if request.method == "POST":
            # save to mongodb database
            name = form.name.data
            num_rounds = form.num_rounds.data
            # workout_content = form.workout_content.data
            workout_content = {'exercise': form.exercise1.data,
                               'num_sets': form.num_sets1.data,
                               'num_reps': form.num_reps1.data}
            scored = form.scored_checkbox.data
            formatted_date = datetime.datetime.today().strftime("%Y-%m-%d")
            # new_workout = Workout(name, num_rounds, workout_content, scored, formatted_date)
            Database.insert('workouts', {'name': name,
                                         'num_rounds': num_rounds,
                                         'scored': scored,
                                         'content': workout_content,
                                         'date': formatted_date})
        # placeholder - will eventually redirect somewhere else
        # that make sense
        return redirect(url_for('workouts.create'))

    return render_template('creation.html', form=form)


@workouts_blueprint.route("/view", methods=["GET"])
def view():
    workouts_with_date = [
        (workout["name"],
         workout["num_rounds"],
         workout["scored"],
         workout["content"],
         workout["date"],
         datetime.datetime.strptime(workout["date"], "%Y-%m-%d").strftime("%b %d")
         )
        for workout in Database.find_all('workouts').sort("date", -1)
    ]

    return render_template("recent.html", workouts=workouts_with_date)

application/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Z-Move</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="{{url_for('static', filename='dynamic_form.js')}}"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="/static/logo2.svg" alt="Z-Move Logo" width="40" height="30" class="d-inline-block align-top">
            Z-Move
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="{{ 'nav-link active' if active_page == 'index' else 'nav-link' }}" href="{{ url_for('index') }}">Home</a>
            </li>
            <li class="nav-item">
              <a class="{{ 'nav-link active' if active_page == 'recent' else 'nav-link' }}" href="{{ url_for('workouts.view') }}">Recent</a>
            </li>
            <li class="nav-item">
              <a class="{{ 'nav-link active' if active_page == 'creation' else 'nav-link' }}" href="{{ url_for('workouts.create') }}">Creation</a>
            </li>
            <li class="nav-item dropdown">
              <a class="{{ 'nav-link dropdown-toggle active' if active_page == 'exercises' else 'nav-link dropdown-toggle' }}" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Exercises
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{{ url_for('exercises.add') }}">Add</a></li>
                <li><a class="dropdown-item" href="{{ url_for('exercises.view') }}">View</a></li>
              </ul>
            </li>
          </ul>
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>

    <div class="container" style="margin-top:30px; max-width: 500px;">

    {% block content %}

    {% endblock %}

    </div>

    <footer class="footer mt-auto py-3 bg-light fixed-bottom">
        <div class="container">
            <span class="text-muted">Made by Zac Binger. Check out my
                <a href="https://github.com/zsbinger" class="link-primary" target="_blank" rel="noreferrer noopener">github</a>
            </span>
        </div>
    </footer>
</body>
</html>

application/templates/home.html
{% extends "base.html" %}

{% block content %}
    <main class="main">
        <h1>Welcome to Z-Move. A dynamic application for workout creation, tracking, and sharing.</h1>
    </main>

{% endblock %}

application/templates/index.html
{% extends "base.html" %}
{% set active_page = 'index' %}

{% block content %}

    <main>
      <img class="profile" src="static/LinkedInZacharyBinger.png" alt="Zac's profile picture." />
      <h1>Starting the creation of the Workout Tracker</h1>
      <p>
        Hello, my name is Zac Binger. I am creating a workout creation and tracking
        web application using HTML, CSS, and Flask (Python).
      </p>
      <p>
        Through extreme flexibility and ease of use, you will be able to
        create and track highly customizable workouts and keep track of
        performance.
      </p>
      <p>One day this app will help you look like this:</p>
      <img class="code" src="CrossFit...Dead.png" alt="How you might look after a good workout." />
    </main>

{% endblock %}

application/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Z-Move</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

</head>

<body background-image: url("../static/bchase-kinney-FMQBLyhD2HU-unsplash.jpg") no-repeat center center fixed;>
    <nav class="nav navbar-expand-lg navbar-dark bg-dark justify-content-center">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img src="/static/logo2.svg" alt="Z-Move Logo" width="40" height="30" class="d-inline-block align-top">
                Z-Move
            </a>
        </div>
    </nav>
    <main class="form-signin w-50 p-3">
      <form>
        <img class="mb-4" src="../static/logo.svg" alt="" width="72" height="57">
        <h1 class="h3 mb-3 fw-normal">Please sign in</h1>
        <label for="inputEmail" class="visually-hidden">Email address</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
        <label for="inputPassword" class="visually-hidden">Password</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
        <div class="checkbox mb-3">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
        <p class="mt-5 mb-3 text-muted">&copy; 2017-2021</p>
      </form>
    </main>

    <footer class="footer mt-auto py-3 bg-light fixed-bottom">
        <div class="container">
            <span class="text-muted">Made by Zac Binger. Check out my
                <a href="https://github.com/zsbinger" class="link-primary" target="_blank" rel="noreferrer noopener">github</a>
            </span>
        </div>
    </footer>
</body>
</html>